# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

build staging:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" --build-arg API_URL=http://api.staging-imoto.jetru.by/graphql .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
  only:
    - master

build demo:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" --build-arg API_URL=http://api.imoto.wiredqa.com/graphql .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
  only:
    - demo

deploy staging:
  stage: deploy
  environment:
    name: staging
    url: http://staging-imoto.jetru.by/
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack Imoto-Staging --service Frontend
    - upgrade --stack Imoto-Staging --service GraphQL
  only:
    - master

deploy demo:
  stage: deploy
  environment:
    name: demo
    url: http://imoto.wiredqa.com/
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack Imoto-Demo --service Frontend
    - upgrade --stack Imoto-Demo --service GraphQL
  only:
    - demo
  when: manual
