ruby '2.3.1'

source 'https://rubygems.org'

gem 'rails', '~> 5.0.3'
gem 'pg'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0', '>= 5.0.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

group :production, :staging do
  gem 'exception_notification'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'pry-byebug'
  gem 'pry'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'binding_of_caller'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'figaro'
  gem 'hirb' # beautify console record view
  gem 'annotate' # Annotate Rails classes with schema and routes info
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'rack-livereload'
  gem 'guard-migrate'
  gem 'guard-annotate'
  gem 'letter_opener'
  gem 'letter_opener_web'
  gem 'rails_db'
  gem 'erd'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'execjs'
gem 'therubyracer'
gem 'less-rails', '~> 2.7.1'

gem 'tether-rails'
gem 'sprockets', '3.6.3'
gem 'haml', '5.0.1'
gem 'slim-rails', '3.1.1'
gem 'devise', '4.3.0'
gem 'mailgun-ruby', '~>1.1.6'
gem 'sentry-raven'
gem 'active_link_to'
gem 'devise-two-factor'
gem 'rqrcode-rails3'
gem 'awesome_print'
gem 'monadic'
gem 'paranoia', '~> 2.2'
gem 'underscore-rails'
gem 'gon'
gem 'inline_svg'
gem 'iban-tools'
gem 'kaminari'
gem 'aasm'
gem 'browser'
gem 'i18n-tasks', '~> 0.9.15'
gem 'bitcoin-ruby'
gem 'turnout'
gem 'rest-client'
gem 'redis'
gem 'grape'
gem 'grape-entity'
gem 'grape-middleware-logger'
gem 'rails-settings-cached'
gem 'foreman'
gem 'vuejs-rails'